# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profesor_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        Form.setMinimumSize(QtCore.QSize(600, 500))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_message = QtWidgets.QWidget()
        self.tab_message.setObjectName("tab_message")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_message)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_message)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.line_edit_message = QtWidgets.QLineEdit(self.tab_message)
        self.line_edit_message.setObjectName("line_edit_message")
        self.verticalLayout_2.addWidget(self.line_edit_message)
        self.button_send_message = QtWidgets.QPushButton(self.tab_message)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_send_message.setFont(font)
        self.button_send_message.setObjectName("button_send_message")
        self.verticalLayout_2.addWidget(self.button_send_message)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_message)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 2, 1, 1)
        self.list_send_messages = QtWidgets.QListWidget(self.tab_message)
        self.list_send_messages.setObjectName("list_send_messages")
        self.gridLayout_7.addWidget(self.list_send_messages, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_message, "")
        self.tab_attendance = QtWidgets.QWidget()
        self.tab_attendance.setObjectName("tab_attendance")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_attendance)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_attendance = QtWidgets.QPushButton(self.tab_attendance)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_attendance.setFont(font)
        self.button_attendance.setObjectName("button_attendance")
        self.verticalLayout.addWidget(self.button_attendance)
        self.line = QtWidgets.QFrame(self.tab_attendance)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(self.tab_attendance)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line_edit_name = QtWidgets.QLineEdit(self.tab_attendance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_name.sizePolicy().hasHeightForWidth())
        self.line_edit_name.setSizePolicy(sizePolicy)
        self.line_edit_name.setObjectName("line_edit_name")
        self.verticalLayout.addWidget(self.line_edit_name)
        self.label_5 = QtWidgets.QLabel(self.tab_attendance)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.line_edit_surname = QtWidgets.QLineEdit(self.tab_attendance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_surname.sizePolicy().hasHeightForWidth())
        self.line_edit_surname.setSizePolicy(sizePolicy)
        self.line_edit_surname.setObjectName("line_edit_surname")
        self.verticalLayout.addWidget(self.line_edit_surname)
        self.label_6 = QtWidgets.QLabel(self.tab_attendance)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.line_edit_index = QtWidgets.QLineEdit(self.tab_attendance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_index.sizePolicy().hasHeightForWidth())
        self.line_edit_index.setSizePolicy(sizePolicy)
        self.line_edit_index.setObjectName("line_edit_index")
        self.verticalLayout.addWidget(self.line_edit_index)
        self.button_add_student = QtWidgets.QPushButton(self.tab_attendance)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_add_student.setFont(font)
        self.button_add_student.setObjectName("button_add_student")
        self.verticalLayout.addWidget(self.button_add_student)
        self.line_2 = QtWidgets.QFrame(self.tab_attendance)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_current_students = QtWidgets.QLabel(self.tab_attendance)
        self.label_current_students.setObjectName("label_current_students")
        self.verticalLayout.addWidget(self.label_current_students)
        self.label_absent_students = QtWidgets.QLabel(self.tab_attendance)
        self.label_absent_students.setObjectName("label_absent_students")
        self.verticalLayout.addWidget(self.label_absent_students)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.line_4 = QtWidgets.QFrame(self.tab_attendance)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.button_delete_student = QtWidgets.QPushButton(self.tab_attendance)
        self.button_delete_student.setObjectName("button_delete_student")
        self.verticalLayout.addWidget(self.button_delete_student)
        self.button_clear_students = QtWidgets.QPushButton(self.tab_attendance)
        self.button_clear_students.setObjectName("button_clear_students")
        self.verticalLayout.addWidget(self.button_clear_students)
        self.button_save_students = QtWidgets.QPushButton(self.tab_attendance)
        self.button_save_students.setObjectName("button_save_students")
        self.verticalLayout.addWidget(self.button_save_students)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.tab_attendance)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.list_widget_students = QtWidgets.QListWidget(self.tab_attendance)
        self.list_widget_students.setObjectName("list_widget_students")
        self.verticalLayout_3.addWidget(self.list_widget_students)
        self.label_8 = QtWidgets.QLabel(self.tab_attendance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.list_widget_absent = QtWidgets.QListWidget(self.tab_attendance)
        self.list_widget_absent.setObjectName("list_widget_absent")
        self.verticalLayout_3.addWidget(self.list_widget_absent)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_attendance, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.combo_box_email = QtWidgets.QComboBox(self.tab)
        self.combo_box_email.setObjectName("combo_box_email")
        self.gridLayout_6.addWidget(self.combo_box_email, 6, 0, 1, 1)
        self.list_widget_emails = QtWidgets.QListWidget(self.tab)
        self.list_widget_emails.setObjectName("list_widget_emails")
        self.gridLayout_6.addWidget(self.list_widget_emails, 11, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 1, 0, 1, 1)
        self.line_edit_password = QtWidgets.QLineEdit(self.tab)
        self.line_edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password.setObjectName("line_edit_password")
        self.gridLayout_6.addWidget(self.line_edit_password, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_email_status = QtWidgets.QLabel(self.tab)
        self.label_email_status.setText("")
        self.label_email_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_email_status.setObjectName("label_email_status")
        self.gridLayout_6.addWidget(self.label_email_status, 9, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 5, 0, 1, 1)
        self.line_edit_email = QtWidgets.QLineEdit(self.tab)
        self.line_edit_email.setObjectName("line_edit_email")
        self.gridLayout_6.addWidget(self.line_edit_email, 2, 0, 1, 1)
        self.button_email = QtWidgets.QPushButton(self.tab)
        self.button_email.setObjectName("button_email")
        self.gridLayout_6.addWidget(self.button_email, 7, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 10, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_6)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.text_edit_emails = QtWidgets.QTextEdit(self.tab)
        self.text_edit_emails.setObjectName("text_edit_emails")
        self.gridLayout_8.addWidget(self.text_edit_emails, 3, 0, 1, 1)
        self.line_edit_subject = QtWidgets.QLineEdit(self.tab)
        self.line_edit_subject.setObjectName("line_edit_subject")
        self.gridLayout_8.addWidget(self.line_edit_subject, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 2, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_8)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.button_activity = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_activity.setFont(font)
        self.button_activity.setObjectName("button_activity")
        self.verticalLayout_6.addWidget(self.button_activity)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.combo_box_student_activity = QtWidgets.QComboBox(self.tab_3)
        self.combo_box_student_activity.setObjectName("combo_box_student_activity")
        self.verticalLayout_6.addWidget(self.combo_box_student_activity)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.gridLayout_10.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem4, 0, 0, 1, 1)
        self.list_widget_activity = QtWidgets.QListWidget(self.tab_3)
        self.list_widget_activity.setObjectName("list_widget_activity")
        self.gridLayout_12.addWidget(self.list_widget_activity, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_12, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_settings)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_change_broad = QtWidgets.QPushButton(self.tab_settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_change_broad.setFont(font)
        self.button_change_broad.setObjectName("button_change_broad")
        self.gridLayout_5.addWidget(self.button_change_broad, 1, 1, 1, 1)
        self.combo_broad = QtWidgets.QComboBox(self.tab_settings)
        self.combo_broad.setObjectName("combo_broad")
        self.gridLayout_5.addWidget(self.combo_broad, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_settings)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_current_data = QtWidgets.QLabel(self.tab_settings)
        self.label_current_data.setText("")
        self.label_current_data.setObjectName("label_current_data")
        self.gridLayout_5.addWidget(self.label_current_data, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_settings, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Input message"))
        self.button_send_message.setText(_translate("Form", "Send"))
        self.label_2.setText(_translate("Form", "List of send messages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_message), _translate("Form", "Send message"))
        self.button_attendance.setText(_translate("Form", "Attendance check"))
        self.label_3.setText(_translate("Form", "Name"))
        self.label_5.setText(_translate("Form", "Surname"))
        self.label_6.setText(_translate("Form", "Index"))
        self.button_add_student.setText(_translate("Form", "Add presence"))
        self.label_current_students.setText(_translate("Form", "Current students: 0"))
        self.label_absent_students.setText(_translate("Form", "Absent students: 0"))
        self.button_delete_student.setText(_translate("Form", "Remove presence"))
        self.button_clear_students.setText(_translate("Form", "Clear attendance list"))
        self.button_save_students.setText(_translate("Form", "Save the attendance list"))
        self.label_4.setText(_translate("Form", "Attendance list"))
        self.label_8.setText(_translate("Form", "Absentee list"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_attendance), _translate("Form", "Attendance"))
        self.label_10.setText(_translate("Form", "Email"))
        self.label_9.setText(_translate("Form", "Password"))
        self.label_11.setText(_translate("Form", "Choose receivers"))
        self.button_email.setText(_translate("Form", "Send"))
        self.label_13.setText(_translate("Form", "Email send to:"))
        self.label_17.setText(_translate("Form", "Subject"))
        self.label_18.setText(_translate("Form", "Content"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Email"))
        self.label_14.setText(_translate("Form", "Check students activity"))
        self.button_activity.setText(_translate("Form", "Check activity"))
        self.label_15.setText(_translate("Form", "Choose student"))
        self.label_16.setText(_translate("Form", "Informations about student activity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Activity"))
        self.button_change_broad.setText(_translate("Form", "Change broadcast ip"))
        self.label_7.setText(_translate("Form", "Select available broadcast ip"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("Form", "Settings"))
        self.label_12.setText(_translate("Form", "This is place for help"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Help"))
