# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profesor_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(479, 347)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_message = QtWidgets.QWidget()
        self.tab_message.setObjectName("tab_message")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_message)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.list_send = QtWidgets.QListWidget(self.tab_message)
        self.list_send.setObjectName("list_send")
        self.gridLayout_7.addWidget(self.list_send, 1, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_message)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_message)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.button_send = QtWidgets.QPushButton(self.tab_message)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_send.setFont(font)
        self.button_send.setObjectName("button_send")
        self.verticalLayout_2.addWidget(self.button_send)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_message)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_message, "")
        self.tab_attendance = QtWidgets.QWidget()
        self.tab_attendance.setObjectName("tab_attendance")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_attendance)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_attendance = QtWidgets.QPushButton(self.tab_attendance)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_attendance.setFont(font)
        self.button_attendance.setObjectName("button_attendance")
        self.verticalLayout_4.addWidget(self.button_attendance)
        self.list_attendance = QtWidgets.QListWidget(self.tab_attendance)
        self.list_attendance.setObjectName("list_attendance")
        self.verticalLayout_4.addWidget(self.list_attendance)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_attendance, "")
        self.tab_progress = QtWidgets.QWidget()
        self.tab_progress.setObjectName("tab_progress")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_progress)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget.addTab(self.tab_progress, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Input message"))
        self.button_send.setText(_translate("Form", "Send"))
        self.label_2.setText(_translate("Form", "List of send messages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_message), _translate("Form", "Send message"))
        self.button_attendance.setText(_translate("Form", "Check attendance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_attendance), _translate("Form", "Attendance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_progress), _translate("Form", "Progress"))
